     Numpy는 Numeric Python의 줄인말이다.
     수학분야 관련된 통계나 연산작업시 사용하는 라이브러리이다.
     과학계산 컴퓨팅과 수학적인 데이터분석에 필요한 기본적인 패키지라고 할 수 있다.

     파이썬의 리스트와 거의 흡사하다
     리스트보다 빠르고 메모리 효율성이 높아서 성능적인 측면에서 훨씬 우위를 차지한다.

In [1]:
import numpy as np

### 1. Numpy배열과 리스트를 비교
#### numpy의 array함수 사용

In [2]:
myList = [1,2,3,4,5]
print(myList)

[1, 2, 3, 4, 5]


In [3]:
myArr = np.array(myList)
print(myArr)

[1 2 3 4 5]


In [4]:
'''
list - python
ndarray - Numpy 
판다스는 2차원 배열로 만들어진다.

numpy => 1차원 구조 (벡터)
pandas => 2차원 구조 (메트릭스)
'''
print(type(myList))
print(type(myArr)) #중요~! ndarray 넘파이 배열, ndarray클라스 타입으로 지원된다.

'''
인덱싱 : 몇번째 인지 가르키는데 사용한다.
슬라이싱 : 몇번째 부터인지 또는 몇 번째까지 또는 몇번부터 몇번까지 출력하기 위해서 자르기 위해서 사용한다.
'''
myList_slice = myList[1:3] # 인덱스 슬라이딩이다. 인덱스 1번부터 2번까지 나온다.
myArr_slice = myArr[1:3]

print(myList_slice)
print(myArr_slice)

myList_slice[0] = -5
myArr_slice[0] =-5

# 리스트 슬라이싱
print(myList_slice)
print(myArr_slice)

# 리스트와 ndarray의 차이점을 정리하자
print(myList) # 안바뀜 카피해서 새로운걸 만든다.
print(myArr) # 바뀜 원본을 바로 바꿔버린다 메모리 효율성이 뛰어나다

<class 'list'>
<class 'numpy.ndarray'>
[2, 3]
[2 3]
[-5, 3]
[-5  3]
[1, 2, 3, 4, 5]
[ 1 -5  3  4  5]


#### numpy의 랜덤함수 사용 

In [5]:
a = np.random.rand(10) # 0부터 1사이의 실수를 랜덤으로 5개의 인덱스를 만들어준다.
print(a)
# ?을 뒤에 사용하면 그에 대한 설명이 나온다.
#np.random.rand?

b = np.random.randint(1,10,6)
print(b)

c = np.random.randn(10) # 가우시간 표준분표
print(c)

[0.80845815 0.96848161 0.34761614 0.76754624 0.73842307 0.0418326
 0.27069521 0.34905467 0.29398196 0.14297884]
[8 2 1 4 9 2]
[-0.60777764  0.5127996  -0.12025864  1.24385972 -1.19290055 -0.31448712
 -0.73893138  0.82580958  0.10027921 -0.25064899]


### 2. numpy배열의 초기화
    초기화 란?
    배열의 생성함과 동시에 최초의 값을 넣는다.
    특정한 값을 할당하는 것을 말한다.
    
    zeros()
    ones()
    arange()

In [6]:
# 1. zeros() 0의 값으로 이뤄진 크기가 10인 배열을 생성

az = np.zeros(10)
print(az)

# 2.  ones() 1의 값으로 이뤄진 크기가 10인 배열을 생성
ao = np.ones(10)
print(ao)
print(np.ones(10)+3)

# 3. eye(3) 3by3 단위의 배열을 생성
ae = np.eye(5)
print(ae)
print('ae + 1 : ',ae[2]*1)
print(ae)

# 4. arange(10) 0부터 10까지 인덱스를 생성한다. (3,9) 하면 3부터 9까지 (2,90,10) 하면 2부터 90까지 10씩 뛰면서 
print(np.arange(2,90,10))
a = np.arange(2,100,10)
print(a)

# 5. full() 모든 배열의 초기화는 어느정도 정리가 된다.
af = np.full((5,5), -11) # np.full(크기,값)
print(af)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
ae + 1 :  [0. 0. 1. 0. 0.]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[ 2 12 22 32 42 52 62 72 82]
[ 2 12 22 32 42 52 62 72 82 92]
[[-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]]


### 3. 리스트와 np배열의 차이점 
    리스트와 np배열의 차이점을 정리한다.

    리스트는 서로다른 타입의 값들이 저장이 가능한 반면에
    np배열은 하나의 자료형만 저장할 수 있다.(더 큰 타입으로 캐스팅 된다. int, string이랑 있으면 string이 더 큰 타입이기 때문에 포함된다.)

In [7]:
L = [1,2,3,'4',5]
number = [1,2,3,4.6,5]
print(L)
print(type(L))
print(number)

[1, 2, 3, '4', 5]
<class 'list'>
[1, 2, 3, 4.6, 5]


In [8]:
narray_1 = np.array(L)
print(narray_1)
print(type(narray_1))

narray_2 = np.array(number)
print(narray_2)
print(type(narray_2))

# 값의 타입을 명시해서 저장할 수도 있다. 이때 dtype 속성을 사용한다.
narray_3 = np.array([1,2,3,4], dtype=np.float) # 같은 자료형만 저장한다.
print(narray_3)


['1' '2' '3' '4' '5']
<class 'numpy.ndarray'>
[1.  2.  3.  4.6 5. ]
<class 'numpy.ndarray'>
[1. 2. 3. 4.]


### 4. Numpy 배열의 속성 혹은 함수
    ndim = 차원값을 반환해줌, shape = 배열의 행과 열, reshape = 행과 열을 바꿔준다, size = 엘레먼트의 갯수, type = 타입
    
    아래부터 나오는 배열은 무조건 np배열.

In [9]:
arr1 = np.array([[1.0, 2, 3],[4, 5, 6]], dtype=np.int32) # 2 by 3으로 나온다. 2행 3열
arr1

# np의 함수를 이용해서 타입, 차원,몇행몇열, 데이터가 총 몇개인지, 출력
print(type(arr1))
print(np.ndim(arr1)) # 2차원은 매트릭스 1차원은 벡터
print(np.shape(arr1)) # 몇행 몇열
print(np.size(arr1))
print('*'*30)
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)
print(arr1.dtype) # dtype과 type을 구분해야한다.
print(type(arr1))
print('*'*30)
# arr1배열의 원소값 타입을 astype()으로 한번에 다른 타입으로 바꿀수 있다.  
print(arr1.dtype)
arr1_1 = arr1.astype(np.float64)
print(arr1_1.dtype)
print('*'*30)
arr2 = np.arange(32)
print(arr2)
print(arr2.shape)
arr2_2 = arr2.reshape(8,4) # 2차원 구조로 바꿔준다.
arr2_2 # 8행 4열

<class 'numpy.ndarray'>
2
(2, 3)
6
******************************
2
(2, 3)
6
int32
<class 'numpy.ndarray'>
******************************
int32
float64
******************************
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
(32,)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])