### 1. 랜덤함수와  seed값 설정하기

여러값을 저장할땐 시드값으로 설정할 수 있다.

#####  seed값 설정하기
    여러명이서 작업할때 랜덤한 값이 나오되, 동일한 랜덤한 값이 나오도록 지정하는 방법
    보통은 한 번만 지정하면 계속해서 사용할수 있다.

    시드값을 설정하지 않을떄는 랜덤한 난수값이 컴퓨터 시간을 기준으로 그때마다 다른 값을 도출하도록 알고리즘이 구현되어있다.
    시드값은 seed()함수안에 숫자를 넣음으로써 수동으로 값을 만들어내는 알고리즘
    seed(0)
    seed(10)
    seed(120)
    seed()는 씨앗과 같이 같은 값을 뿌리면 같은 결과가 나온다.

In [1]:
import numpy as np
np.random.seed(0) # seed값은 0혹은 양의 정수만 가능하다. 

In [2]:
import numpy as np
arr1 = np.random.randn(4,4)
arr1

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433]])

In [3]:
arr2 = np.arange(1,10)
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#모양이 같아야만 reshape을 사용해서 정의 할 수 있다.
# reshape은 매우 중요하다.
arr3 = arr2.reshape(3, 3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr4 = np.random.randint(10,20,16).reshape(4, 4) #16개
arr4
#print(arr4)

#arr4_1 = np.random.randint(10, size=9)
#print(arr4_1)

array([[12, 13, 18, 11],
       [13, 13, 13, 17],
       [10, 11, 19, 19],
       [10, 14, 17, 13]])

### 2. 인덱싱, 슬라이싱

In [6]:
narray = np.arange(5)
narray

array([0, 1, 2, 3, 4])

In [7]:
# 1. 인덱싱과 슬라이싱으로 값 추출하기
print(narray[:-3]) # 인덱스에 음수가 붙으면 뒤에서 n번째로 이해해야 한다.
print(narray[1:]) # 이음을 말한다 n번부터 ~ 라고 이해함.
print(narray[:4]) # ~ n-1까지
print(narray[:]) 
print(narray[2:4]) 
print()

[0 1]
[1 2 3 4]
[0 1 2 3]
[0 1 2 3 4]
[2 3]



In [8]:
arr4 # 2차원 4by 4

array([[12, 13, 18, 11],
       [13, 13, 13, 17],
       [10, 11, 19, 19],
       [10, 14, 17, 13]])

In [9]:
print(arr4[0][2])
print(arr4[0,2])
print(arr4[1])
print(arr4[:,3:4])
print(arr4[:,1:3])


18
18
[13 13 13 17]
[[11]
 [17]
 [19]
 [13]]
[[13 18]
 [13 13]
 [11 19]
 [14 17]]


### 3. 인덱싱과 조건 슬라이싱
    열거된 배열의 값에서 논리연산잔 혹은 where함수를 사용해서 
    내가 원하는 값을 가져올 수 있어야 한다.

In [10]:
arr2 = np.random.randn(4,4)

#1. 논리 연산자 사용
arr2[arr2<0]

#2. 0보자 작은값들(음수)는 전부다 0으로 바꿔보자
arr2[arr2<0] = 0 
arr2 # 원본이 바뀐다.

#3. where 함수를 사용
arr2_w = np.where(arr2>0, arr2, -1) # 3항 연산자 arr2>0이 트루면 arr2을 반환하고 펄스면 -1을 리턴한다.
arr2_w


array([[ 0.59124281, -1.        , -1.        , -1.        ],
       [-1.        , -1.        , -1.        , -1.        ],
       [-1.        ,  0.90734594,  0.81526991,  0.22909795],
       [-1.        ,  0.47752547,  1.29269823, -1.        ]])

In [11]:
# 중요!!
exam_a = np.array([[1,2],[3,4],[5,6]])
exam_a

# 2보다 큰 값만 추출
result = exam_a>2
print(exam_a[result])

# 2보다 큰 값만 추출 하고 2보다 작은 값은 0으로
exam_a = np.where(exam_a > 2, exam_a, 0)
print(exam_a)

[3 4 5 6]
[[0 0]
 [3 4]
 [5 6]]


### 4. Numpy 통계함수
##### sum(), min(), max(), mean(), argmin(), argmax(), comsum()

In [12]:
print(np.sum(arr4))
print(arr4)
print('sum 0 :',np.sum(arr4, 0)) # 아래쪽으로 행으로 기준 
print('sum 1 :',np.sum(arr4, 1)) # 왼쪽으로  열로 기준
print('argmax 0 :',np.argmax(arr4, 0))
print('argmax 1 :',np.argmax(arr4, 1))
print('argmin 0 :',np.argmin(arr4, 0))
print('argmin 1 :',np.argmin(arr4, 1))

223
[[12 13 18 11]
 [13 13 13 17]
 [10 11 19 19]
 [10 14 17 13]]
sum 0 : [45 51 67 60]
sum 1 : [54 56 59 54]
argmax 0 : [1 3 2 2]
argmax 1 : [2 3 2 2]
argmin 0 : [2 2 1 0]
argmin 1 : [3 0 0 0]
